### ISSUE TITLE
no function 'build_current_book_part' found in package 'SticsPubRTools'

### ISSUE THREAD

**Issue by eric-casellas** [SticsRPacks/SticsPubRTools#1]
# no function 'build_current_book_part' found in package 'SticsPubRTools'

addin **build current book part** not working
error message : 
`no function 'build_current_book_part' found in package 'SticsPubRTools'`

I think the build_current_book_part function is missing in the NAMESPACE file of the package

**Comment by plecharpent** [comment]
Eric,
Thanks you for your feedback.
Exporting this function now fixed and help updated.
